---
- name: Check OS Version on Localhost
  hosts: localhost
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Print OS version
      ansible.builtin.debug:
        msg: "The OS version is {{ ansible_distribution }} {{ ansible_distribution_version }}"
